# Server configuration
server.port=8080

# WebFlux configuration
spring.webflux.base-path=/

# Logging
logging.level.root=INFO
logging.level.com.thelastwar=DEBUG

# Reactor Netty configuration
spring.reactor.netty.ioWorkerCount=4
spring.reactor.netty.shutdown-quiet-period=0

# Application name
spring.application.name=rest-gateway
