package com.thelastwar.matching;

import io.micrometer.core.instrument.*;
import io.micrometer.core.instrument.simple.SimpleMeterRegistry;

import java.util.concurrent.atomic.AtomicLong;

/**
 * Metrics collector for matching engine operations.
 * 
 * Tracks:
 * - Orders processed per second
 * - Match latency distribution (p50, p95, p99)
 * - Queue depth
 * - Trade count
 * - Rejection and cancellation rates
 * 
 * All metrics are exported via Micrometer and can be scraped by Prometheus.
 * Target: p99 latency < 15 µs with < 1% profiling overhead.
 */
public class MatchingEngineMetricsCollector {
    
    private final MeterRegistry registry;
    private final String engineName;
    
    // Counters
    private final Counter ordersProcessed;
    private final Counter tradesGenerated;
    private final Counter ordersRejected;
    private final Counter ordersCancelled;
    private final Counter ordersModified;
    
    // Timers for latency tracking
    private final Timer matchLatency;
    private final Timer cancelLatency;
    private final Timer modifyLatency;
    
    // Gauges for queue depth
    private final AtomicLong queueDepth;
    
    /**
     * Creates a new MatchingEngineMetricsCollector instance with a SimpleMeterRegistry.
     * 
     * @param engineName Unique name for this matching engine instance
     */
    public MatchingEngineMetricsCollector(String engineName) {
        this(new SimpleMeterRegistry(), engineName);
    }
    
    /**
     * Creates a new MatchingEngineMetricsCollector instance.
     * 
     * @param registry Micrometer registry to register metrics with
     * @param engineName Unique name for this matching engine instance
     */
    public MatchingEngineMetricsCollector(MeterRegistry registry, String engineName) {
        this.registry = registry;
        this.engineName = engineName;
        
        // Initialize counters
        this.ordersProcessed = Counter.builder("matching.orders.processed")
                .description("Number of orders processed by the matching engine")
                .tag("engine", engineName)
                .register(registry);
        
        this.tradesGenerated = Counter.builder("matching.trades.generated")
                .description("Number of trades generated by the matching engine")
                .tag("engine", engineName)
                .register(registry);
        
        this.ordersRejected = Counter.builder("matching.orders.rejected")
                .description("Number of orders rejected by the matching engine")
                .tag("engine", engineName)
                .register(registry);
        
        this.ordersCancelled = Counter.builder("matching.orders.cancelled")
                .description("Number of orders cancelled")
                .tag("engine", engineName)
                .register(registry);
        
        this.ordersModified = Counter.builder("matching.orders.modified")
                .description("Number of orders modified")
                .tag("engine", engineName)
                .register(registry);
        
        // Initialize timers with percentiles for latency tracking
        this.matchLatency = Timer.builder("matching.latency.match")
                .description("Order matching latency distribution")
                .tag("engine", engineName)
                .publishPercentiles(0.5, 0.95, 0.99)
                .publishPercentileHistogram()
                .register(registry);
        
        this.cancelLatency = Timer.builder("matching.latency.cancel")
                .description("Order cancellation latency distribution")
                .tag("engine", engineName)
                .publishPercentiles(0.5, 0.95, 0.99)
                .publishPercentileHistogram()
                .register(registry);
        
        this.modifyLatency = Timer.builder("matching.latency.modify")
                .description("Order modification latency distribution")
                .tag("engine", engineName)
                .publishPercentiles(0.5, 0.95, 0.99)
                .publishPercentileHistogram()
                .register(registry);
        
        // Initialize gauges
        this.queueDepth = new AtomicLong(0);
        Gauge.builder("matching.queue.depth", queueDepth, AtomicLong::get)
                .description("Current queue depth for pending orders")
                .tag("engine", engineName)
                .register(registry);
    }
    
    /**
     * Records that an order was processed.
     */
    public void recordOrderProcessed() {
        ordersProcessed.increment();
    }
    
    /**
     * Records match latency for an order.
     * 
     * @param latencyNanos Latency in nanoseconds
     */
    public void recordMatchLatency(long latencyNanos) {
        matchLatency.record(latencyNanos, java.util.concurrent.TimeUnit.NANOSECONDS);
    }
    
    /**
     * Records that a trade was generated.
     */
    public void recordTradeGenerated() {
        tradesGenerated.increment();
    }
    
    /**
     * Records that an order was rejected.
     */
    public void recordOrderRejected() {
        ordersRejected.increment();
    }
    
    /**
     * Records that an order was cancelled.
     */
    public void recordOrderCancelled() {
        ordersCancelled.increment();
    }
    
    /**
     * Records cancellation latency.
     * 
     * @param latencyNanos Latency in nanoseconds
     */
    public void recordCancelLatency(long latencyNanos) {
        cancelLatency.record(latencyNanos, java.util.concurrent.TimeUnit.NANOSECONDS);
    }
    
    /**
     * Records that an order was modified.
     */
    public void recordOrderModified() {
        ordersModified.increment();
    }
    
    /**
     * Records modification latency.
     * 
     * @param latencyNanos Latency in nanoseconds
     */
    public void recordModifyLatency(long latencyNanos) {
        modifyLatency.record(latencyNanos, java.util.concurrent.TimeUnit.NANOSECONDS);
    }
    
    /**
     * Updates the queue depth gauge.
     * 
     * @param depth Current queue depth
     */
    public void updateQueueDepth(long depth) {
        queueDepth.set(depth);
    }
    
    /**
     * Gets the total number of orders processed.
     * 
     * @return order count
     */
    public long getOrdersProcessedCount() {
        return (long) ordersProcessed.count();
    }
    
    /**
     * Gets the total number of trades generated.
     * 
     * @return trade count
     */
    public long getTradesGeneratedCount() {
        return (long) tradesGenerated.count();
    }
    
    /**
     * Gets the total number of orders rejected.
     * 
     * @return rejection count
     */
    public long getOrdersRejectedCount() {
        return (long) ordersRejected.count();
    }
    
    /**
     * Gets the total number of orders cancelled.
     * 
     * @return cancellation count
     */
    public long getOrdersCancelledCount() {
        return (long) ordersCancelled.count();
    }
    
    /**
     * Gets the total number of orders modified.
     * 
     * @return modification count
     */
    public long getOrdersModifiedCount() {
        return (long) ordersModified.count();
    }
    
    /**
     * Gets the current queue depth.
     * 
     * @return queue depth
     */
    public long getQueueDepth() {
        return queueDepth.get();
    }
    
    /**
     * Gets the p99 match latency in nanoseconds.
     * 
     * @return p99 latency in nanoseconds
     */
    public double getP99MatchLatencyNanos() {
        io.micrometer.core.instrument.distribution.HistogramSnapshot snapshot = matchLatency.takeSnapshot();
        var percentileValues = snapshot.percentileValues();
        for (var p : percentileValues) {
            if (p.percentile() == 0.99) {
                return p.value(java.util.concurrent.TimeUnit.NANOSECONDS);
            }
        }
        return 0.0;
    }
    
    /**
     * Gets the p95 match latency in nanoseconds.
     * 
     * @return p95 latency in nanoseconds
     */
    public double getP95MatchLatencyNanos() {
        io.micrometer.core.instrument.distribution.HistogramSnapshot snapshot = matchLatency.takeSnapshot();
        var percentileValues = snapshot.percentileValues();
        for (var p : percentileValues) {
            if (p.percentile() == 0.95) {
                return p.value(java.util.concurrent.TimeUnit.NANOSECONDS);
            }
        }
        return 0.0;
    }
    
    /**
     * Gets the p50 match latency in nanoseconds.
     * 
     * @return p50 latency in nanoseconds
     */
    public double getP50MatchLatencyNanos() {
        io.micrometer.core.instrument.distribution.HistogramSnapshot snapshot = matchLatency.takeSnapshot();
        var percentileValues = snapshot.percentileValues();
        for (var p : percentileValues) {
            if (p.percentile() == 0.5) {
                return p.value(java.util.concurrent.TimeUnit.NANOSECONDS);
            }
        }
        return 0.0;
    }
    
    /**
     * Gets throughput in orders per second.
     * 
     * @return orders per second
     */
    public double getThroughput() {
        return ordersProcessed.count();
    }
    
    /**
     * Gets the MeterRegistry for external access.
     * 
     * @return meter registry
     */
    public MeterRegistry getRegistry() {
        return registry;
    }
    
    /**
     * Gets the engine name.
     * 
     * @return engine name
     */
    public String getEngineName() {
        return engineName;
    }
}
